# Generated by Django 4.1 on 2025-01-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=25)),
                ('categoryimage', models.ImageField(upload_to='')),
                ('categorydesc', models.CharField(max_length=100)),
            ],
        ),
    ]
