# Generated by Django 4.1 on 2025-01-14 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_tbl_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_location',
            fields=[
                ('locationid', models.AutoField(primary_key=True, serialize=False)),
                ('locationname', models.CharField(max_length=25)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_district')),
            ],
        ),
    ]
