# Generated by Django 4.1 on 2025-01-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_tbl_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_equipment',
            fields=[
                ('equipmentid', models.AutoField(primary_key=True, serialize=False)),
                ('equipmentname', models.CharField(max_length=25)),
                ('equipmentimage', models.ImageField(upload_to='')),
                ('equipmentdesc', models.CharField(max_length=100)),
                ('equipmentstock', models.IntegerField()),
            ],
        ),
    ]
