# Generated by Django 4.1 on 2025-01-17 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_tbl_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_equipment',
            name='equipmentdesc',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='Tbl_scholarship',
            fields=[
                ('scholarshipid', models.AutoField(primary_key=True, serialize=False)),
                ('scholarshipname', models.CharField(max_length=25)),
                ('scholarshipdesc', models.CharField(max_length=300)),
                ('criteria', models.CharField(max_length=300)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('link', models.CharField(max_length=300)),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_category')),
            ],
        ),
    ]
