# Generated by Django 4.1 on 2025-01-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_alter_tbl_equipment_equipmentdesc_tbl_scholarship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_scholarship',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tbl_scholarship',
            name='startdate',
            field=models.DateField(),
        ),
    ]
