# Generated by Django 4.1 on 2025-01-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_alter_tbl_scholarship_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_scholarship',
            name='startdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
