# Generated by Django 4.1 on 2025-02-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_alter_tbl_scholarship_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_equipment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
