# Generated by Django 4.1 on 2025-01-28 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GuestApp', '0005_alter_tbl_disabledperson_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_enquiry',
            fields=[
                ('enquiryid', models.AutoField(primary_key=True, serialize=False)),
                ('enquiry', models.CharField(max_length=25)),
                ('status', models.CharField(default='', max_length=25)),
                ('institutionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_institution')),
                ('personid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_disabledperson')),
            ],
        ),
    ]
