# Generated by Django 4.1 on 2025-01-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisabledPersonApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_enquiry',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
