# Generated by Django 4.1 on 2025-02-11 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_tbl_equipment_amount'),
        ('GuestApp', '0005_alter_tbl_disabledperson_email'),
        ('DisabledPersonApp', '0002_tbl_enquiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_request',
            fields=[
                ('requestid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='', max_length=25)),
                ('requesteddate', models.DateField(auto_now_add=True, null=True)),
                ('equipmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_equipment')),
                ('personid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_disabledperson')),
            ],
        ),
    ]
