# Generated by Django 4.1 on 2025-02-13 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DisabledPersonApp', '0003_tbl_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_payment',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('paymentdate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=25)),
                ('amount', models.IntegerField()),
                ('requestid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DisabledPersonApp.tbl_request')),
            ],
        ),
    ]
