# Generated by Django 4.1 on 2025-03-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisabledPersonApp', '0004_tbl_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_request',
            name='requesteddate',
            field=models.DateField(null=True),
        ),
    ]
