# Generated by Django 4.1 on 2025-03-12 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0005_alter_tbl_disabledperson_email'),
        ('AdminApp', '0008_tbl_equipment_amount'),
        ('DisabledPersonApp', '0005_alter_tbl_request_requesteddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_scholarshipreq',
            fields=[
                ('requestid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='', max_length=25)),
                ('course', models.CharField(max_length=25)),
                ('income', models.IntegerField()),
                ('accountno', models.IntegerField()),
                ('institutionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_institution')),
                ('personid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_disabledperson')),
                ('scholarshipid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_scholarship')),
            ],
        ),
    ]
