# Generated by Django 4.1 on 2025-03-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisabledPersonApp', '0006_tbl_scholarshipreq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_scholarshipreq',
            name='accountno',
            field=models.BigIntegerField(),
        ),
    ]
