# Generated by Django 4.1 on 2025-03-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisabledPersonApp', '0007_alter_tbl_scholarshipreq_accountno'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
