# Generated by Django 4.1 on 2025-03-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisabledPersonApp', '0008_tbl_request_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='totalamount',
            field=models.IntegerField(null=True),
        ),
    ]
