# Generated by Django 4.1 on 2025-02-04 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DisabledPersonApp', '0002_tbl_enquiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_schedule',
            fields=[
                ('scheduleid', models.AutoField(primary_key=True, serialize=False)),
                ('scheduledate', models.DateField()),
                ('status', models.CharField(default='', max_length=25)),
                ('enquiryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DisabledPersonApp.tbl_enquiry')),
            ],
        ),
    ]
