# Generated by Django 4.1 on 2025-02-21 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_tbl_equipment_amount'),
        ('GuestApp', '0005_alter_tbl_disabledperson_email'),
        ('InstitutionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_request2',
            fields=[
                ('requestid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='', max_length=25)),
                ('requesteddate', models.DateField(auto_now_add=True, null=True)),
                ('equipmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_equipment')),
                ('institutionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_institution')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_payment2',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('paymentdate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=25)),
                ('amount', models.IntegerField()),
                ('requestid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InstitutionApp.tbl_request2')),
            ],
        ),
    ]
