# Generated by Django 4.1 on 2025-02-26 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0005_alter_tbl_disabledperson_email'),
        ('InstitutionApp', '0002_tbl_request2_tbl_payment2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_jobposting',
            fields=[
                ('jobid', models.AutoField(primary_key=True, serialize=False)),
                ('jobtitle', models.CharField(max_length=50)),
                ('jobdesc', models.CharField(max_length=100)),
                ('requirments', models.CharField(max_length=100)),
                ('deadline', models.DateField(auto_now_add=True, null=True)),
                ('contactemail', models.CharField(max_length=50)),
                ('jobimage', models.ImageField(upload_to='')),
                ('institutionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_institution')),
            ],
        ),
    ]
