# Generated by Django 4.1 on 2025-02-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstitutionApp', '0003_tbl_jobposting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_jobposting',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
