# Generated by Django 4.1 on 2025-03-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstitutionApp', '0004_alter_tbl_jobposting_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_request2',
            name='requesteddate',
            field=models.DateField(null=True),
        ),
    ]
