# Generated by Django 4.1 on 2025-03-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstitutionApp', '0005_alter_tbl_request2_requesteddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request2',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_request2',
            name='totalamount',
            field=models.IntegerField(null=True),
        ),
    ]
