# Generated by Django 4.1 on 2025-01-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_login',
            name='status',
            field=models.CharField(default='', max_length=25),
        ),
    ]
