# Generated by Django 4.1 on 2025-01-21 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_alter_tbl_scholarship_enddate_and_more'),
        ('GuestApp', '0002_tbl_login_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_institution',
            fields=[
                ('institutionid', models.AutoField(primary_key=True, serialize=False)),
                ('institutionname', models.CharField(max_length=25)),
                ('regnumber', models.CharField(max_length=25)),
                ('contactno', models.BigIntegerField()),
                ('email', models.CharField(max_length=25)),
                ('percentage', models.CharField(max_length=25)),
                ('institutiondesc', models.CharField(max_length=300)),
                ('websiteurl', models.CharField(max_length=25)),
                ('institutionimage', models.ImageField(upload_to='')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_category')),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_location')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_login')),
            ],
        ),
    ]
