# Generated by Django 4.1 on 2025-01-22 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_alter_tbl_scholarship_enddate_and_more'),
        ('GuestApp', '0003_tbl_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_disabledperson',
            fields=[
                ('personid', models.AutoField(primary_key=True, serialize=False)),
                ('personname', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
                ('contactno', models.BigIntegerField()),
                ('email', models.CharField(max_length=25)),
                ('percentage', models.CharField(max_length=25)),
                ('disabilitydetails', models.CharField(max_length=300)),
                ('pname', models.CharField(max_length=25)),
                ('pcontact', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('idproof', models.ImageField(upload_to='')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_category')),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_location')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_login')),
            ],
        ),
    ]
