# Generated by Django 4.1 on 2025-01-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0004_tbl_disabledperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_disabledperson',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
